### ISSUE TITLE
OTST_TI_PATCH_PASSENGER

### ISSUE THREAD

**Issue by LucFen** [UnionInternationalCheminsdeFer/OSDM-testing#21]
Description
Scenario includes:
•	POST /offers request based on a tripSearchCriteria, containing origin, destination and departure time
•	POST /bookings request based on the response of the offer response. 
•	Patch of the passenger name using patch /bookings/{bookingId}/passengers/{passengerId}

Scenario
1.	Generate and send a post /offers request with a tripSearchCriteria, containing origin, destination and departure time
2.	Generate and send a post /bookings request using one offer in the post /offers response
3.	Generate and send a patch /bookings/{bookingId}/passengers/{passengerId} request using the bookingId and passengerId contained in the post /bookings response

**Comment by jspetrak** [comment]
Duplicates #18
